org: michaeluskov
app: kewebrocks
service: kewebrocks

frameworkVersion: "3"

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  timeout: 100
  environment:
    BOT_TOKEN: ${param:BOT_TOKEN}
    MONGO_URL: ${param:MONGO_URL}
    STORAGE_KEY: ${param:STORAGE_KEY}
    STORAGE_SECRET: ${param:STORAGE_SECRET}

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
          
  photosgetter:
    handler: photos_getter.handler
    events:
      - http:
          path: /photos
          method: ANY

plugins:
  - serverless-plugin-typescript
